- name: Create node_exporter user
  user:
    name: node_exporter
    shell: /usr/sbin/nologin
    system: true
    create_home: false

- name: Download Node Exporter archive
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.8.2/node_exporter-1.8.2.linux-amd64.tar.gz
    dest: /tmp/node_exporter-1.8.2.linux-amd64.tar.gz
    mode: "0644"

- name: Extract Node Exporter archive
  unarchive:
    src: /tmp/node_exporter-1.8.2.linux-amd64.tar.gz
    dest: /tmp
    remote_src: true

- name: Copy Node Exporter binary
  copy:
    src: /tmp/node_exporter-1.8.2.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    owner: node_exporter
    group: node_exporter
    mode: "0755"
    remote_src: true

- name: Create Node Exporter systemd service
  copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Node Exporter
      After=network.target

      [Service]
      User=node_exporter
      Group=node_exporter
      Type=simple
      ExecStart=/usr/local/bin/node_exporter

      [Install]
      WantedBy=multi-user.target
    owner: root
    group: root
    mode: "0644"

- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Ensure Node Exporter is running and enabled
  systemd:
    name: node_exporter
    state: started
    enabled: true