[web]
web-01 ansible_host=<WEB_01_FLOATING_IP> ansible_user=ubuntu ansible_ssh_private_key_file=../lab-key.pem

[db]
db-01 ansible_host=<DB_01_FLOATING_IP> ansible_user=ubuntu ansible_ssh_private_key_file=../lab-key.pem

[monitor]
monitor-01 ansible_host=<MONITOR_01_FLOATING_IP> ansible_user=ubuntu ansible_ssh_private_key_file=../lab-key.pem

[test]
test-01 ansible_host=<TEST_01_FLOATING_IP> ansible_user=ubuntu ansible_ssh_private_key_file=../lab-key.pem

[all_servers:children]
web
db
monitor
test